// <auto-generated />
using System;
using ApiData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiData.Migrations
{
    [DbContext(typeof(EventContext))]
    partial class EventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiModels.Event.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date");

                    b.Property<string>("ImageUrl");

                    b.Property<int?>("LocationID");

                    b.Property<string>("Name");

                    b.Property<string>("OnlineUrl");

                    b.Property<decimal>("Price");

                    b.HasKey("EventID");

                    b.HasIndex("LocationID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ApiModels.Event.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.HasKey("LocationID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("ApiModels.Event.Session", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abstract");

                    b.Property<int>("Duration");

                    b.Property<int?>("EventID");

                    b.Property<string>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("Presenter");

                    b.HasKey("SessionID");

                    b.HasIndex("EventID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ApiModels.Event.Event", b =>
                {
                    b.HasOne("ApiModels.Event.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");
                });

            modelBuilder.Entity("ApiModels.Event.Session", b =>
                {
                    b.HasOne("ApiModels.Event.Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventID");
                });
#pragma warning restore 612, 618
        }
    }
}
